name = "Create and Irons"
author = "ClassicSlime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce0f14082006c889c76fccc242d1b7e190cc2a409c69f4f5c4d8f9b1687a2b90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
