name = "Create and Irons"
author = "ClassicSlime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6f1d4b6f24106faec964fa20c000b817a29c39766f5302e069502576aa0aecb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
