#--------------------------------------------------------------------
#|                     FUNDAMENTAL PRINCIPLES CLIENT CONFIGS         |
#--------------------------------------------------------------------
#
[others]
	fatigueCounterXOffset = 0
	fatigueCounterYOffset = 0
